/**
 * SYNTHETIC SAMPLE DATA - NOT MARKET DATA.
 *
 * Every value here is generated by pricing contracts through this project's own
 * Black-Scholes engine at a chosen volatility. Nothing was observed in a market
 * and nothing should be traded on it.
 *
 * It exists for exactly two purposes:
 *   1. Demonstrating the engine end-to-end without network access.
 *   2. Giving the test suite and CI a deterministic chain to scan.
 *
 * It is NOT a fallback for the real data path. `scan.ts --live` uses the actual
 * providers, and when a provider fails the CLI reports the failure rather than
 * quietly substituting this. Presenting generated numbers as market data would
 * defeat the entire point of the application.
 *
 * Because the chain is priced by the same model the scanner uses, the numbers
 * are internally consistent. A linear volatility skew is applied so far strikes
 * are not underpriced relative to a real surface, but it remains a crude
 * approximation of one.
 */

import { blackScholes, expirationInstant, yearsToExpiry } from '@stealth/core';
import type { Bar } from '@stealth/core';
import type { ContractSnapshot } from '@stealth/core';

export interface SampleUnderlying {
  readonly symbol: string;
  readonly spot: number;
  /** At-the-money implied volatility; skew is applied per strike. */
  readonly impliedVolatility: number;
  /** Realised volatility of the generated price history. */
  readonly bars: readonly Bar[];
}

const RISK_FREE = 0.045;

/** Deterministic pseudo-random generator, so runs are reproducible. */
function mulberry32(seed: number): () => number {
  let a = seed;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * Generates a plausible uptrending daily series ending at `spot`.
 *
 * Drift must dominate noise over the sample window or the series does not
 * actually trend: at 0.0006/day drift against 0.018/day vol, cumulative drift
 * over 300 days is 0.18 while noise is 0.018*sqrt(300) = 0.31, so the "uptrend"
 * is swamped and the trend classifier correctly reports neutral. These defaults
 * put drift comfortably ahead of noise so the sample resembles the kind of name
 * a put seller would actually be screening.
 */
export function sampleBars(
  spot: number,
  days: number,
  seed: number,
  drift = 0.0028,
  vol = 0.011,
): Bar[] {
  const random = mulberry32(seed);
  const closes: number[] = [];
  let price = spot * 0.72;

  for (let i = 0; i < days; i += 1) {
    // Box-Muller for a normal shock.
    const u1 = Math.max(random(), 1e-9);
    const u2 = random();
    const shock = Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
    price *= 1 + drift + vol * shock;
    closes.push(price);
  }

  // Rescale so the series ends exactly at spot.
  const scale = spot / (closes[closes.length - 1] as number);

  return closes.map((close, i) => {
    const c = close * scale;
    const range = c * 0.012;
    return {
      date: new Date(Date.UTC(2025, 0, 1) + i * 86_400_000)
        .toISOString()
        .slice(0, 10),
      open: c - range * 0.3,
      high: c + range,
      low: c - range,
      close: c,
      volume: 1_500_000 + Math.floor(random() * 2_000_000),
    };
  });
}

/**
 * Equity volatility skew.
 *
 * Real put chains are not priced at a single volatility: implied volatility
 * rises as strikes fall, because downside protection is bid up. Pricing a flat
 * surface made adjacent strikes differ by less than their own bid/ask spread,
 * so every generated credit spread came out below the minimum credit-to-width
 * floor and the PCS and CCS tabs returned nothing. That was the sample data
 * being unrepresentative, not the spread engine rejecting wrongly.
 *
 * A linear skew in moneyness is crude next to a real surface, but it restores
 * the property that actually matters here: strikes further out of the money
 * carry proportionally more premium than a flat surface implies.
 */
const SKEW_SLOPE = 0.9;

function skewedVolatility(
  atmVolatility: number,
  spot: number,
  strike: number,
): number {
  const moneyness = (spot - strike) / spot;
  return Math.max(0.03, atmVolatility * (1 + SKEW_SLOPE * moneyness));
}

/**
 * Builds a put chain priced by Black-Scholes with a volatility skew.
 *
 * Bid/ask are placed symmetrically around theoretical value with a spread that
 * widens as the contract goes further out of the money, which is the one
 * microstructure effect that materially affects liquidity scoring.
 */
export function samplePutChain(
  underlying: SampleUnderlying,
  expirationIso: string,
  now: Date,
): ContractSnapshot[] {
  const expiration = expirationInstant(expirationIso);
  const years = yearsToExpiry(now, expiration);
  const { spot, impliedVolatility } = underlying;

  const contracts: ContractSnapshot[] = [];
  const step = spot > 200 ? 5 : 1;
  const lowest = Math.round((spot * 0.8) / step) * step;
  const highest = Math.round((spot * 1.02) / step) * step;

  for (let strike = lowest; strike <= highest; strike += step) {
    const contractIv = skewedVolatility(impliedVolatility, spot, strike);
    const priced = blackScholes({
      spot,
      strike,
      timeToExpiry: years,
      volatility: contractIv,
      riskFreeRate: RISK_FREE,
      right: 'put',
    });

    const theoretical = priced.price;
    if (theoretical < 0.02) continue;

    const otmFraction = Math.max(0, (spot - strike) / spot);
    // Spread widens with distance OTM; floor of 2 cents.
    const halfSpread = Math.max(0.01, theoretical * (0.008 + otmFraction * 0.18));
    const bid = Math.max(0.01, roundCents(theoretical - halfSpread));
    const ask = roundCents(theoretical + halfSpread);

    // Open interest and volume concentrate near the money.
    const nearness = Math.exp(-((otmFraction / 0.06) ** 2));
    const openInterest = Math.round(200 + 9000 * nearness);
    const volume = Math.round(5 + 900 * nearness);

    contracts.push({
      occSymbol: `${underlying.symbol}${expirationIso.replace(/-/g, '').slice(2)}P${String(
        Math.round(strike * 1000),
      ).padStart(8, '0')}`,
      strike,
      expiration,
      right: 'put',
      bid,
      ask,
      last: roundCents(theoretical),
      volume,
      openInterest,
      impliedVolatility: contractIv,
      delta: priced.delta,
      theta: priced.theta,
      vega: priced.vega,
    });
  }

  return contracts;
}

function roundCents(value: number): number {
  return Math.round(value * 100) / 100;
}

/** A small illustrative universe. */
export const SAMPLE_UNIVERSE: readonly Omit<SampleUnderlying, 'bars'>[] = [
  { symbol: 'APP', spot: 462, impliedVolatility: 0.42 },
  { symbol: 'NVDA', spot: 178, impliedVolatility: 0.38 },
  { symbol: 'MU', spot: 121, impliedVolatility: 0.45 },
  { symbol: 'SNDK', spot: 64, impliedVolatility: 0.52 },
  { symbol: 'NBIS', spot: 39, impliedVolatility: 0.66 },
];
