/**
 * Command-line scanner.
 *
 * Two modes, and the distinction is deliberate and load-bearing:
 *
 *   --live    Fetches from the real providers. This is the actual application.
 *             If a provider fails, the CLI SAYS SO and exits non-zero. It never
 *             falls back to sample data, because a scanner that silently
 *             substitutes generated numbers for market data is worse than one
 *             that fails.
 *
 *   --sample  Runs the identical pipeline over a chain generated by this
 *             project's own pricing model. Every printed number is clearly
 *             marked synthetic. Useful for demonstrating the engine and for CI,
 *             where there is no network.
 *
 * Both paths run the SAME scanner, scorer and renderer. Only the data source
 * differs.
 */

import {
  classifyMarketRegime,
  computeIndicators,
  ivHvRatio,
  ivRank,
  scanCsp,
  volatilityRichnessLabel,
  DEFAULT_CSP_CONFIG,
  type ContractSnapshot,
  type CspCandidate,
  type RegimeAssessment,
  type ScanContext,
} from '@stealth/core';
import {
  YahooProvider,
  createYahooClient,
  enrichContracts,
  isProviderError,
} from '@stealth/data';
import {
  SAMPLE_UNIVERSE,
  sampleBars,
  samplePutChain,
} from './sample-chain';

// ---------------------------------------------------------------------------
// Terminal rendering
// ---------------------------------------------------------------------------

const useColor = process.stdout.isTTY !== false && !process.env.NO_COLOR;
const c = (code: string) => (s: string) => (useColor ? `[${code}m${s}[0m` : s);

const bold = c('1');
const green = c('38;5;42');
const red = c('38;5;203');
const amber = c('38;5;214');
const cyan = c('38;5;51');
const white = c('97');
const grey = c('38;5;244');

function rule(width = 78): string {
  return grey('─'.repeat(width));
}

function scoreColor(score: number): (s: string) => string {
  if (score >= 75) return green;
  if (score >= 55) return amber;
  return red;
}

function pad(value: string, width: number): string {
  return value.length >= width ? value.slice(0, width) : value.padEnd(width);
}

function padStart(value: string, width: number): string {
  return value.length >= width ? value.slice(0, width) : value.padStart(width);
}

function pctStr(value: number | null, digits = 1): string {
  return value === null ? '—' : `${(value * 100).toFixed(digits)}%`;
}

function renderRegimeHeader(regime: RegimeAssessment, asOf: Date): void {
  const label = regime.label.toUpperCase().replace('-', ' ');
  const tone =
    regime.label === 'bullish'
      ? green
      : regime.label === 'bearish'
        ? red
        : amber;

  console.log('');
  console.log(
    `${bold(white('MARKET REGIME'))}   ${tone(bold(label))}   ${grey(
      `score ${regime.score.toFixed(0)}`,
    )}   ${grey(asOf.toISOString().replace('T', ' ').slice(0, 16) + 'Z')}`,
  );

  if (regime.volatilityOverride) {
    console.log(
      `               ${amber('! volatility override active')} ${grey(
        `(directional read: ${regime.directionalLabel})`,
      )}`,
    );
  }

  const passed = regime.components.filter((x) => x.passed).map((x) => x.label);
  const failed = regime.components.filter((x) => !x.passed).map((x) => x.label);
  if (passed.length > 0) console.log(`               ${green('✓')} ${grey(passed.join(' · '))}`);
  if (failed.length > 0) console.log(`               ${red('✗')} ${grey(failed.join(' · '))}`);
  if (regime.missing.length > 0) {
    console.log(`               ${grey(`unavailable: ${regime.missing.join(', ')}`)}`);
  }
  console.log('');
}

function renderTable(candidates: readonly CspCandidate[], limit: number): void {
  console.log(
    bold(
      white(
        pad('TICKER', 8) +
          padStart('STRIKE', 8) +
          padStart('DTE', 5) +
          padStart('SCORE', 7) +
          padStart('DELTA', 7) +
          padStart('PREM', 7) +
          padStart('OTM%', 7) +
          padStart('ANN.YLD', 9) +
          padStart('P(OTM)', 8) +
          padStart('OI', 7),
      ),
    ),
  );
  console.log(rule(73));

  for (const candidate of candidates.slice(0, limit)) {
    const m = candidate.metrics;
    const tone = scoreColor(candidate.score.score);
    console.log(
      cyan(pad(candidate.symbol, 8)) +
        padStart(m.strike.toFixed(0), 8) +
        padStart(String(m.dte), 5) +
        tone(bold(padStart(candidate.score.score.toFixed(0), 7))) +
        padStart(m.delta.toFixed(3), 7) +
        padStart(m.premium.toFixed(2), 7) +
        padStart(pctStr(m.distanceOtmPct), 7) +
        green(padStart(pctStr(m.annualizedYieldSimple, 0), 9)) +
        padStart(pctStr(m.probabilityOtm, 0), 8) +
        padStart(
          candidate.contract.openInterest === null
            ? '—'
            : String(candidate.contract.openInterest),
          7,
        ),
    );
  }
  console.log('');
}

function renderBreakdown(candidate: CspCandidate): void {
  const m = candidate.metrics;
  const tone = scoreColor(candidate.score.score);

  console.log(rule());
  console.log(
    `${bold(cyan(candidate.symbol))} ${white(`$${m.strike} PUT`)} ${grey(
      `${candidate.contract.expiration.toISOString().slice(0, 10)} · ${m.dte} DTE`,
    )}`,
  );
  console.log('');
  console.log(
    `${bold('CSP SCORE')}  ${tone(bold(candidate.score.score.toFixed(0)))}${grey(' / 100')}`,
  );
  console.log('');

  for (const component of candidate.score.components) {
    const filled = Math.round((component.earned / component.weight) * 12);
    const bar = green('█'.repeat(filled)) + grey('░'.repeat(12 - filled));
    console.log(
      `  ${pad(component.label, 20)} ${bar} ${padStart(
        `${component.earned.toFixed(1)} / ${component.weight.toFixed(0)}`,
        11,
      )}   ${grey(component.detail)}`,
    );
  }

  if (candidate.score.unavailable.length > 0) {
    console.log(
      `  ${grey(`weight redistributed from: ${candidate.score.unavailable.join(', ')}`)}`,
    );
  }

  console.log('');
  for (const factor of candidate.score.positiveFactors) {
    console.log(`  ${green('✓')} ${factor}`);
  }
  for (const factor of candidate.score.negativeFactors) {
    console.log(`  ${amber('⚠')} ${factor}`);
  }

  console.log('');
  renderExpectedMoveLadder(candidate);
  console.log('');
}

/** The strike-positioning visualisation: where the trade sits vs expected move. */
function renderExpectedMoveLadder(candidate: CspCandidate): void {
  const m = candidate.metrics;
  if (m.expectedMove === null || m.expectedMoveLower === null) return;

  const spot = m.strike + (m.distanceOtmPct * m.strike) / (1 - m.distanceOtmPct);
  const upper = spot + m.expectedMove;
  const levels: Array<{ price: number; label: string; tone: (s: string) => string; marker: string }> = [
    { price: upper, label: 'Expected move +1σ', tone: grey, marker: '┤' },
    { price: spot, label: 'Current price', tone: white, marker: '●' },
    { price: m.strike, label: 'CSP strike', tone: cyan, marker: '◆' },
    { price: m.expectedMoveLower, label: 'Expected move −1σ', tone: grey, marker: '┤' },
    { price: m.breakeven, label: 'Break-even', tone: green, marker: '┤' },
  ].sort((a, b) => b.price - a.price);

  for (const level of levels) {
    console.log(
      `    ${padStart(`$${level.price.toFixed(2)}`, 10)} ${grey('─────')}${level.tone(
        level.marker,
      )} ${level.tone(level.label)}`,
    );
  }
}

// ---------------------------------------------------------------------------
// Pipeline
// ---------------------------------------------------------------------------

interface ScanInput {
  readonly symbol: string;
  readonly spot: number;
  readonly bars: readonly import('@stealth/core').Bar[];
  readonly contracts: readonly ContractSnapshot[];
  readonly impliedVolatility: number;
}

function runScan(inputs: readonly ScanInput[], now: Date, regime: RegimeAssessment) {
  const all: CspCandidate[] = [];
  const rejections: Record<string, number> = {};
  let examined = 0;

  for (const input of inputs) {
    const indicators = computeIndicators(input.bars, input.spot);

    const context: ScanContext = {
      symbol: input.symbol,
      now,
      spot: input.spot,
      riskFreeRate: 0.045,
      dividendYield: 0,
      technicals: {
        price: input.spot,
        ema20: indicators.ema20,
        ema50: indicators.ema50,
        ema200: indicators.ema200,
        rsi14: indicators.rsi14,
        atrPercent14: indicators.atrPercent14,
        hv20: indicators.hv20,
        support: indicators.levels.nearestSupport?.price ?? null,
        resistance: indicators.levels.nearestResistance?.price ?? null,
        week52High: indicators.range52w?.high ?? null,
        week52Low: indicators.range52w?.low ?? null,
        trendScore: indicators.trend.score,
        trendComplete: indicators.trend.complete,
      },
      // No accumulated IV history on a first run - exactly the cold-start case.
      ivRank: ivRank(input.impliedVolatility, []),
      ivHv: ivHvRatio(input.impliedVolatility, indicators.hv20),
      earnings: null,
      regime,
    };

    const summary = scanCsp(input.contracts, context, DEFAULT_CSP_CONFIG);
    all.push(...summary.candidates);
    examined += summary.examined;
    for (const [reason, count] of Object.entries(summary.rejections)) {
      rejections[reason] = (rejections[reason] ?? 0) + count;
    }

    if (summary.candidates.length > 0) {
      const richness = volatilityRichnessLabel(context.ivRank, context.ivHv);
      console.log(
        `  ${grey('·')} ${cyan(pad(input.symbol, 6))} ${grey(
          `${summary.examined} contracts → ${summary.candidates.length} candidates · ${richness}`,
        )}`,
      );
    }
  }

  all.sort((a, b) => b.score.score - a.score.score);
  return { candidates: all, examined, rejections };
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

async function liveInputs(symbols: readonly string[], now: Date): Promise<ScanInput[]> {
  const provider = new YahooProvider({ client: createYahooClient() });
  const inputs: ScanInput[] = [];

  for (const symbol of symbols) {
    const quote = await provider.getQuote(symbol);
    const from = new Date(now.getTime() - 400 * 86_400_000);
    const history = await provider.getHistoricalPrices(symbol, { from });
    const expirations = await provider.getExpirations(symbol);

    const target = expirations.expirations.find((e) => {
      const dte = (e.getTime() - now.getTime()) / 86_400_000;
      return dte >= DEFAULT_CSP_CONFIG.minDte && dte <= DEFAULT_CSP_CONFIG.maxDte;
    });
    if (!target) continue;

    const chain = await provider.getOptionsChain(symbol, target);

    // Yahoo supplies no Greeks, so they are derived here.
    const { contracts, stats } = enrichContracts(chain.puts, {
      spot: quote.price,
      now,
      riskFreeRate: 0.045,
      deriveMissingIv: true,
    });
    console.log(
      `  ${grey('·')} ${cyan(pad(symbol, 6))} ${grey(
        `${stats.total} puts · ${stats.computed} Greeks computed locally · ${stats.unavailable} unavailable`,
      )}`,
    );

    const atm = contracts.reduce<number | null>((best, contract) => {
      if (contract.impliedVolatility === null) return best;
      return best === null ||
        Math.abs(contract.strike - quote.price) <
          Math.abs((best as number) - quote.price)
        ? contract.impliedVolatility
        : best;
    }, null);

    inputs.push({
      symbol,
      spot: quote.price,
      bars: history.bars,
      contracts: contracts.map((contract) => ({
        occSymbol: contract.occSymbol,
        strike: contract.strike,
        expiration: contract.expiration,
        right: contract.right,
        bid: contract.bid,
        ask: contract.ask,
        last: contract.last,
        volume: contract.volume,
        openInterest: contract.openInterest,
        impliedVolatility: contract.impliedVolatility,
        delta: contract.greeks?.delta ?? null,
        theta: contract.greeks?.theta ?? null,
        vega: contract.greeks?.vega ?? null,
      })),
      impliedVolatility: atm ?? 0.3,
    });
  }

  return inputs;
}

function sampleInputs(now: Date): ScanInput[] {
  // Roughly three weeks out, landing inside the default 7-30 DTE window.
  const expiry = new Date(now.getTime() + 21 * 86_400_000).toISOString().slice(0, 10);

  return SAMPLE_UNIVERSE.map((underlying, i) => {
    const bars = sampleBars(underlying.spot, 300, 1000 + i);
    return {
      symbol: underlying.symbol,
      spot: underlying.spot,
      bars,
      contracts: samplePutChain({ ...underlying, bars }, expiry, now),
      impliedVolatility: underlying.impliedVolatility,
    };
  });
}

async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const live = args.includes('--live');
  const limit = Number(args.find((a) => a.startsWith('--top='))?.split('=')[1] ?? 10);
  const symbols = (args.find((a) => a.startsWith('--symbols='))?.split('=')[1] ?? '')
    .split(',')
    .filter(Boolean);

  const now = new Date();

  console.log('');
  console.log(bold(white('  STEALTH')) + grey('  ·  options opportunity scanner'));
  console.log('');

  if (!live) {
    console.log(
      amber('  SAMPLE MODE — every figure below is generated by this project’s own'),
    );
    console.log(
      amber('  pricing model. It is NOT market data. Run with --live for real quotes.'),
    );
    console.log('');
  }

  // The regime engine needs index data; in sample mode it is stated as unknown
  // rather than invented, which exercises the missing-data path honestly.
  let regime: RegimeAssessment;
  let inputs: ScanInput[];

  if (live) {
    const provider = new YahooProvider({ client: createYahooClient() });
    const [spy, qqq] = await Promise.all([
      provider.getQuote('SPY'),
      provider.getQuote('QQQ'),
    ]);
    const from = new Date(now.getTime() - 400 * 86_400_000);
    const [spyBars, qqqBars] = await Promise.all([
      provider.getHistoricalPrices('SPY', { from }),
      provider.getHistoricalPrices('QQQ', { from }),
    ]);
    const spyInd = computeIndicators(spyBars.bars, spy.price);
    const qqqInd = computeIndicators(qqqBars.bars, qqq.price);
    let vix: { level: number; change5d: number | null } | null = null;
    try {
      const vixQuote = await provider.getQuote('^VIX');
      vix = {
        level: vixQuote.price,
        change5d:
          vixQuote.previousClose === null
            ? null
            : vixQuote.price - vixQuote.previousClose,
      };
    } catch {
      vix = null;
    }

    regime = classifyMarketRegime({
      spy: { price: spy.price, ema20: spyInd.ema20, ema50: spyInd.ema50, ema200: spyInd.ema200 },
      qqq: { price: qqq.price, ema20: qqqInd.ema20, ema50: qqqInd.ema50, ema200: qqqInd.ema200 },
      vix,
    });

    console.log(grey('  Fetching chains…'));
    inputs = await liveInputs(
      symbols.length > 0 ? symbols : ['AAPL', 'MSFT', 'NVDA'],
      now,
    );
  } else {
    inputs = sampleInputs(now);
    regime = classifyMarketRegime({
      spy: { price: 604, ema20: 598, ema50: 588, ema200: 551 },
      qqq: { price: 523, ema20: 518, ema50: 508, ema200: 471 },
      vix: { level: 15.2, change5d: -0.9 },
      breadth: 0.62,
    });
  }

  renderRegimeHeader(regime, now);

  console.log(bold(white('SCANNING')));
  const result = runScan(inputs, now, regime);
  console.log('');
  console.log(
    grey(
      `  ${result.examined} contracts examined · ${result.candidates.length} passed all filters`,
    ),
  );

  const rejectionSummary = Object.entries(result.rejections)
    .sort((a, b) => b[1] - a[1])
    .map(([reason, count]) => `${count} ${reason}`)
    .join(' · ');
  if (rejectionSummary) console.log(grey(`  rejected: ${rejectionSummary}`));
  console.log('');

  if (result.candidates.length === 0) {
    console.log(amber('  No candidates passed the current filters.'));
    console.log('');
    return;
  }

  console.log(bold(white('TOP CASH-SECURED PUT OPPORTUNITIES')));
  console.log('');
  renderTable(result.candidates, limit);

  renderBreakdown(result.candidates[0] as CspCandidate);

  if (!live) {
    console.log(
      amber('  Reminder: sample mode. These are model-generated contracts, not quotes.'),
    );
    console.log('');
  }
}

main().catch((error: unknown) => {
  console.error('');
  if (isProviderError(error)) {
    // Typed provider failures get a specific, actionable message - and we do
    // NOT fall back to sample data.
    console.error(red(`  ${error.kind.toUpperCase()}: ${error.message}`));
    console.error(
      grey(
        `  provider=${error.provider} operation=${error.operation}` +
          (error.symbol ? ` symbol=${error.symbol}` : '') +
          ` retryable=${error.retryable}`,
      ),
    );
  } else {
    console.error(red(`  Scan failed: ${String(error)}`));
  }
  console.error('');
  process.exitCode = 1;
});
